### PR TITLE
fix: fix #1698 - Notification email doesn't contain Message-Id header

### LINKED ISSUE #1698: Notification email doesn't contain Message-ID header
## Describe the bug
Mail notifications don't have a `Message-ID` header. Although RFC  5322 doesn't say there MUST be a `Message-ID`, there are several reasons why an email should have a unique identifier, which is essential for

- tracking message threads and conversations
- detecting duplicate messages
- creating proper reply chains (along with `In-Reply-To` and `References` headers)
- debugging mail delivery issues
- proper spam detection systems

## Steps to reproduce
1. Enable mail notifications on OC instance
2. Share file with user
3. Mail notification is sent

## Expected behaviour
- an email containing a `Message-ID` header.

## Actual behaviour
- Mail doesn't have a `Message-ID` header
- receiving MTA also logs

```
Oct 23 16:33:17 mail postfix/smtpd[3264004]: 45B42856898: client=unknown[172.18.0.4], sasl_method=PLAIN, sasl_username=relay
Oct 23 16:33:17 mail postfix/cleanup[3264026]: 45B42856898: message-id=<>
Oct 23 16:33:17 mail postfix/qmgr[107384]: 45B42856898: from=<notification@opencloud.test>, size=3079, nrcpt=1 (queue active)
```

## Setup
Latest `docker compose` stack with configured and enabled `notifications` service.

### PR DESCRIPTION
**Pull request by schweigisito**
## Description
This PR fixes #1698, an issue that notification emails don't contain `Message-Id` headers.

## Related Issue
- Fixes #1698 

## Motivation and Context
This adds a quite important mail header which is needed to achieve

- tracking message threads and conversations
- detecting duplicate messages
- creating proper reply chains (along with In-Reply-To and References headers)
- debugging mail delivery issues
- proper spam detection systems

## How Has This Been Tested?
Dev Docker image has been built and deployed using opencloud-eu/opencloud-compose

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation added

### CODE REVIEW

File: services/notifications/pkg/channels/channels.go [hunk 1]
```diff
@@ -3,9 +3,12 @@ package channels
 
 import (
 	"context"
+	"crypto/rand"
```
Comment (rhafer) [inline services/notifications/pkg/channels/channels.go:6]: I am not really sure if we need crypto save random numbers for the message ids. I guess a properly seeded pseudo random numbers from `math/crypto` could also be enough for that purpose.
But I guess it's fine this way as well.
